apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-green

spec:
 replicas: 4
 selector:
  matchLabels:
   app: green
 template:
  metadata:
   name: temp-1
   labels:
    app: green
  spec:
   containers:
    - name: green-container
      image: abhipraydh96/green:latest
      ports:
        - containerPort: 80
