---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-1
spec:
 replicas: 5
 selector:
  matchLabels:
   app: demoapp

 template:
  metadata:
   name: template-01
   labels:
    app: demoapp
  spec:
   containers:
   - name: cont-01
     image: nginx
     ports:
     - containerPort: 80
...