## create namespace using manifest
---
apiVersion: v1
kind: Namespace
metadata:
 name: prod
...
##Create Pod in specific namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: prod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
...
