### example:
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-fluentd
spec:
  containers:
# Main Container: Nginx
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
      ports:
        - containerPort: 80
    # Sidecar Container: Fluentd
    - name: fluentd
      image: fluent/fluentd:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
  # Shared Volume for Log Communication
  volumes:
    - name: shared-logs
      emptyDir: {}
...      
