apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-green

spec:
 replicas: 2
 selector:
  app: green
  
 template:
  metadata:
   name: temp-1
   labels:
    app: green
  spec:
   containers:
    - name: green-container
      image: abhipraydh96/green:latest
      ports:
        - containerPort: 80
