apiVersion: v1
kind: ReplicationController
metadata:
 name: rc-01

spec:
 replicas: 3
 selector:
    app: demoapp
 template:
   metadata:
    labels:
      app: demoapp
   spec:
    containers:
    - name: cont-1
      image: nginx
      ports:
      - containerPort: 80
